import os

DISCORD_TOKEN = os.environ["DISCORD_TOKEN"]

DEV_GUILD_ID = int(os.environ.get("DEV_GUILD_ID")) if os.environ.get("DEV_GUILD_ID") else None

COMPOSE_FILES_DIRECTORY_PATH = os.environ["COMPOSE_FILES_DIRECTORY_PATH"]

GAME_SERVERS_DIRECTORY_PATH = os.environ["GAME_SERVERS_DIRECTORY_PATH"]

BACKUPS_DIRECTORY_PATH = os.environ["BACKUPS_DIRECTORY_PATH"]


